### ISSUE TITLE
极客时间 115编号的课程无法下载

### ISSUE THREAD

**Issue by wajika** [jachinlin/geektime_dl#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
 [root@docker1 ~]# geektime ebook 115
'column_type'
执行下载命令会提示column_type
**Additional context**

**Comment by flyhigher139** [comment]
我这边在下载100以内的专栏时，会报这个问题

**Comment by wajika** [comment]
我是python3.7.1

**Comment by jachinlin** [comment]
应该跟py版本没关系，

方便的话贴下 geektime.log 相关日志。

或者把 **sqlite3.db** 删了再试下

**Comment by wajika** [comment]
好 我试试。 geektime.log这文件在哪里能找到？

**Comment by wajika** [comment]
删除sqlite3.db 后解决问题
