### ISSUE TITLE
在下载82课程mobi电子书时会出错

### ISSUE THREAD

**Issue by wajika** [jachinlin/geektime_dl#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
报错信息：
*************************************************************
 Amazon kindlegen(Linux) V2.9 build 1028-0897292 
 A command line e-book compiler 
 Copyright Amazon.com and its Affiliates 2014 
*************************************************************

Info(prcgen):I1047: Added metadata dc:Title        "Java核心技术36讲[更新完毕]"
Info(prcgen):I1047: Added metadata dc:Creator      "jachinlin.github.io"
Error(core):E1008: Failed conversion to unicode. The resulting string may contain wrong characters.
Info(prcgen):I1002: Parsing files  0000045
Warning(inputpreprocessor):W29007: Rejected unknown tag: <pid>
      in file: /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/第30讲|Java程序运行在Docker等容器环境有哪些新问题？.html     line: 0000046
Warning(inputpreprocessor):W29004: Forcefully closed opened Tag: <a href="https://docs.oracle.com/javacomponents/jmc-5-4/jfr-runtime-guide/about.htm#JFRUH173">
      in file: /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/第33讲|后台服务出现明显“变慢”，谈谈你的诊断思路？.html     line: 0000030
Warning(prcgen):W14009: media file not specified  
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/bf/06/bf6e3f87d162595ddaa5d0786c0ed806.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/17/0e/17ed56811412ccab5024a119511e0f0e.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/04/3f/0432ac1e431256fb894144aa2e66b03f.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/98/5f/98d02b66e1d3fdf8cc1f7f7c6f974b5f.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/c9/10/c9fae97c8a4954cb91b59dc7e59ab710.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/75/61/7559562971dc2eadd8fd03f02980a461.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/f8/d9/f8b11bdcb1559e472b77e23fcf184dd9.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/d2/12/d286554382cbba791f85e667ea124e12.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/4a/4f/4ab17456a34278a8ca18de54fea76f4f.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/3d/b8/3d70890354f556d1b3acbc2f2fdd99b8.jpg
Warning(prcgen):W14010: media file not found  /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/https:/static001.geekbang.org/resource/image/35/bf/35c9a5cab69eae467adb7d85d76d41bf.jpg
Error(prcgen):E21018: Enhanced Mobi building failure, while parsing content in the file. Content: <img> in file: /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/周末福利|一份Java工程师必读书单.html line: 9
cp: cannot stat ‘./ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/Java核心技术36讲[更新完毕].mobi’: No such file or directory

**Additional context**

**Comment by jachinlin** [comment]
>Error(prcgen):E21018: Enhanced Mobi building failure, while parsing content in the file. Content:  in file: /root/ebook/2bd634d0-ceb0-4458-afe5-a66ab471882a/周末福利|一份Java工程师必读书单.html line: 9

我没购买该专栏，试了下把免费试读的文章专程拜访电子书没问题

你这个可能是**周末福利|一份Java工程师必读书单.html**这个文档有特殊标签或者其他什么，方便的话可以把这个文档发给我，我看下。我邮箱你找下，就在这个项目某个角落里

**Comment by jachinlin** [comment]
fixed

**Comment by wajika** [comment]
文件已经发送

**Comment by jachinlin** [comment]
><img style="margin: 0 auto" src="https://static001.geekbang.org/resource/image/cf/5b/cfdeee6412d6ed593c44a6c4f513d35b.jpg">

这个文档的img标签有一些奇怪的属性值，kindlegen不能识别罢工了，新版本已修复

**Comment by kerraway** [comment]
是需要用 git 代码安装吗？我用 pip install -U geektime_dl 命令安装，转换电子书的时候遇到了同样的问题。

**Comment by wajika** [comment]
今天又试了一次 ，依然会报错 line 7
Error(prcgen):E21018: Enhanced Mobi building failure, while parsing content in the file. Content: <img> in file: /home/wjk/ebook/304a3383-74cb-4f7e-9023-39f00937cece/周末福利-一份Java工程师必读书单.html line: 7
cp: cannot stat ‘/home/wjk/ebook/304a3383-74cb-4f7e-9023-39f00937cece/Java核心技术36讲[更新完毕].mobi’: No such file or directory
```

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>周末福利-一份Java工程师必读书单</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
</head>
<body>
<h1>周末福利-一份Java工程师必读书单</h1>

<p>你好，我是杨晓峰。今天这期周末福利，<span class="orange">我整理了几本自己在学习和使用Java时用过的参考书</span>，把它们分享与你。在专栏里，有不少>同学留言让我推荐一些参考书。另外，我认为，书是个好的系统化知识来源，但更多提高还是来源于实践、阅读源码、技术交流等，毕竟书籍也很难完全跟上技术和架构
的变革，另外我也尽量缩减了书单的长度。</p><p><strong>关于夯实Java编程基础，我推荐Bruce Eckel的《Java编程思想》（Thinking in Java）</strong>，非常有>名的经典书籍。这本书的特点是，不仅仅介绍Java编程的基础知识点，也会思考编程中的各种选择与判断，包括穿插设计模式的使用，作者从理论到实践意义从不同的角
度进行探讨，构建稳固的Java编程知识体系。</p><img></img><p>当然这本书也有不足之处，毕竟每个人的基础不太一样，如果你完全没有Java编程基础，也可以考虑其
他的参考书，例如 <strong>《Java核心技术》</strong>。</p><p>另外，这两本书的部分内容已经多少有点过时了，尤其是《Java编程思想》。例如，目前很少会需要>学习Java桌面图形类库等，较新的语法和API当然也没有包含，我的建议是尽管忽略过时内容，适当补充Java新技术的学习。</p><p>提到经典，自然也少不了 <strong>>《Effective Java》</strong>，这本书的英文第三版已经在国内上市，涵盖了Java 7到Java 9的各种新特性。严格来说，这本书不算是一本基础书籍，但当你有一定基>础后，还是非常建议通读一下的。关于这本书的阅读，我的建议是边学习边回顾，在吸收书中的经验时，多去想想自己在实际应用中是如何处理的。虽然《Effective Java》的具体章节可能是从某个点出发，但可以说都是对Java、JVM、面向对象等各种知识的综合运用，对于设计和实现高质量的代码很有帮助。</p><!-- [[[read_end]]] --><p><img src="d60a6fb3-953d-4911-9508-1f679193de4e.jpg" alt=""><br>
<feff><br>
```
