### ISSUE TITLE
python安装无法登录

### ISSUE THREAD

**Issue by waterdrops** [jachinlin/geektime_dl#16]
#### python 相关信息

> pyenv  1.2.9-2-g6309aaf2
> pyenv-virtualenv  1.1.3 (virtualenv unknown)
> Python 3.6.8
> pip 18.1 from /Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/pip (python 3.6)

#### 系统信息
> Darwin Warrens-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64

#### 错误信息：
`('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))`

**Comment by jachinlin** [comment]
是指执行 `login`命令时失败吗？

可以贴下geektime.log吗

**Comment by waterdrops** [comment]
> 是指执行 `login`命令时失败吗？
> 
> 可以贴下geektime.log吗

感谢回复，执行 geektime login 命令时返回的日志信息如下：另外个人博客里面的邮箱地址不正确，我发送邮件失败

> og_time=2019-01-18 17:51:10,296	levelname=ERROR	process=82798	exception=Traceback (most recent call last):
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>    chunked=chunked)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
>    self._validate_conn(conn)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
>    conn.connect()
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
>    ssl_context=context)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
>    return context.wrap_socket(sock, server_hostname=server_hostname)
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 407, in wrap_socket
>    _context=self, _session=session)
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 817, in __init__
>    self.do_handshake()
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 1077, in do_handshake
>    self._sslobj.do_handshake()
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 689, in do_handshake
>    self._sslobj.do_handshake()
> onnectionResetError: [Errno 54] Connection reset by peer

> uring handling of the above exception, another exception occurred:

> raceback (most recent call last):
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
>    timeout=timeout
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
>    _stacktrace=sys.exc_info()[2])
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
>    raise six.reraise(type(error), error, _stacktrace)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
>    raise value.with_traceback(tb)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>    chunked=chunked)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
>    self._validate_conn(conn)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
>    conn.connect()
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
>    ssl_context=context)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
>    return context.wrap_socket(sock, server_hostname=server_hostname)
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 407, in wrap_socket
>    _context=self, _session=session)
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 817, in __init__
>    self.do_handshake()
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 1077, in do_handshake
>    self._sslobj.do_handshake()
>  File "/Users/warren/.pyenv/versions/3.6.8/lib/python3.6/ssl.py", line 689, in do_handshake
>    self._sslobj.do_handshake()
> rllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

> uring handling of the above exception, another exception occurred:

> raceback (most recent call last):
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/geektime_dl/cli/command.py", line 63, in main
>    o.work(args)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/geektime_dl/cli/command.py", line 26, in work
>    return self.run(args)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/geektime_dl/cli/login.py", line 49, in run
>    gk.login(account, password, area)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/geektime_dl/utils/__init__.py", line 22, in wrapper
>    return func(self, *args, **kwargs)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/geektime_dl/data_client/gk_apis.py", line 54, in login
>    resp = requests.post(url, headers=headers, json=data, timeout=10)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/requests/api.py", line 116, in post
>    return request('post', url, data=data, json=json, **kwargs)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/requests/api.py", line 60, in request
>    return session.request(method=method, url=url, **kwargs)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
>    resp = self.send(prep, **send_kwargs)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
>    r = adapter.send(request, **kwargs)
>  File "/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
>    raise ConnectionError(err, request=request)
> equests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
	location=/Users/warren/.pyenv/versions/3.6.8/envs/geektime/lib/python3.6/site-packages/geektime_dl/cli/command.py:74

**Comment by jachinlin** [comment]
不清楚是什么问题，我这边也复现不了。

要不尝试下
https://stackoverflow.com/questions/38853972/python-client-error-connection-reset-by-peer

**Comment by waterdrops** [comment]
> 不清楚是什么问题，我这边也复现不了。
> 
> 要不尝试下
> https://stackoverflow.com/questions/38853972/python-client-error-connection-reset-by-peer

好的，感谢，我先把这个issue关掉
