### ISSUE TITLE
生成出来的mobi图片变成感叹号

### ISSUE THREAD

**Issue by stevennight** [jachinlin/geektime_dl#19]
作者你好，我想请问一下我这边生成出来的MOBI图片变成感叹号看不了，图片的代码貌似是这样的。
`<img src="../images/00001.jpeg" alt calibre_f3fa75ca98eb4413a4ee413f20f60226="0" style="-webkit-column-break-inside: avoid;">`
貌似生成时会出现这种警告：
Warning(prcgen):W14010: media file not found  /output/ebook/108336b5-8d70-4180-85d7-7db31b450584/9101bd5e-aba7-4931-bc84-8e9b767c9118.jpg
看了一下目录，只有“/output/ebook/专栏名”这个目录
Windows docker 环境， 执行命令为：docker run -v /d/Study/geektime:/output -i -t --rm geektime ebook 110 --enable-comments

**Comment by jachinlin** [comment]
sorry，这个问题复现不出来，我这边只有W14012 mp4不存在的警告

108336b5-8d70-4180-85d7-7db31b450584 只是个临时文件，电子书制作完成后会被删除。

你可以试一下加上`--sourc-only`参数，这样就只会生成中间文件，主要是一堆html，然后再看看有问题的图片那里，在html中长什么样

**Comment by stevennight** [comment]
随便找了个LINUX小鸡去下载，没有出现这种问题，只出现了
Warning(inputpreprocessor):W29008: Tag rejected due to improper usage: </hr>
      in file: /home/stevennight/ebook/f1371caa-5fa6-4781-a23f-a26339a7452a/春节7天练|Day7：贪心、分治、回溯和动态规划.html     line: 0000047
应该无伤大雅吧…

windows docker 环境下试了一下，还是这样子。 生成出来的HTML 图片是正常的，没有什么问题。
