### ISSUE TITLE
可以手动指定一个包含html文件的目录，打包成mobi文件吗？

### ISSUE THREAD

**Issue by wajika** [jachinlin/geektime_dl#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jachinlin** [comment]
可以试下[kindle_maker](https://github.com/jachinlin/kindle_maker)

**Comment by wajika** [comment]
> 可以试下[kindle_maker](https://github.com/jachinlin/kindle_maker)

手动创建有问题，麻烦看看
