### ISSUE TITLE
windows用虚拟机使用centos7 报错

### ISSUE THREAD

**Issue by Eviwang** [jachinlin/geektime_dl#27]
![image](https://user-images.githubusercontent.com/9146097/56567413-723d9500-65e7-11e9-82bf-c8b76c8ead49.png)

**Comment by Eviwang** [comment]
![image](https://user-images.githubusercontent.com/9146097/56567967-96e63c80-65e8-11e9-9341-6a98955b7013.png)

**Comment by jachinlin** [comment]
python3 only

docker的使用方式参考readme吧，图二第二条命令跟docker没什么关系
