### ISSUE TITLE
windows 10使用docker for desktop跑的docker命令，提出成功，但找不到输出目录。

### ISSUE THREAD

**Issue by sheng-jie** [jachinlin/geektime_dl#28]
十分感谢，这么棒的功能。

但有一个问题：windows 10使用docker for desktop跑的docker命令，提出成功，但找不到输出目录。

**Comment by jachinlin** [comment]
> 十分感谢，这么棒的功能。
> 
> 但有一个问题：windows 10使用docker for desktop跑的docker命令，提出成功，但找不到输出目录。

sorry, windows docker 没用过，我也不知道输出目录在哪。

或者你把操作命令发下 我google下

**Comment by sheng-jie** [comment]
> > 十分感谢，这么棒的功能。
> > 但有一个问题：windows 10使用docker for desktop跑的docker命令，提出成功，但找不到输出目录。
> 
> sorry, windows docker 没用过，我也不知道输出目录在哪。
> 
> 或者你把操作命令发下 我google下

依然感谢，我自己琢磨吧。
