### ISSUE TITLE
Got an error when try to install it

### ISSUE THREAD

**Issue by zhixau** [jachinlin/geektime_dl#34]
**Is your feature request related to a problem? Please describe.**
Get an error when install geektime_dl in windows, with python 3.7.3 & python 3.5.4.
Try to upgrade setuptools to resolve it, but failed.

****
![image](https://user-images.githubusercontent.com/19568956/60228301-d836e900-98c4-11e9-8d95-c5f07c76596f.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jachinlin** [comment]
看到 windows 就头疼。。。
