### ISSUE TITLE
求教指令

### ISSUE THREAD

**Issue by klkucan** [jachinlin/geektime_dl#40]
用的docker版本，在docker run -v `pwd`:/output -it --rm geektime ebookbatch --all --enable-comments指令中`pwd`是指的需要输入密码？？？还有，执行后发现并没有得到所有的课程，而且请问下载后的html在哪里放着？？

**Comment by jachinlin** [comment]
\`pwd\` 表示当前目录，如果需要换成其他目录，直接改就行了，比如改成 \`/tmp\`

下载后的mobi和html文件会保存在 上面说的 **上面设置的目录/ebook** 下
