### ISSUE TITLE
docker登陆成功显示尚未登陆

### ISSUE THREAD

**Issue by wuwenrui** [jachinlin/geektime_dl#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wuwenrui** [comment]
docker 下执行
`docker run geektime login --account=** --password=** --area=86`之后显示登陆成功，但是执行
`docker run geektime  query` 却显示   尚未登录, 可以先 geektime login 以便查看更详细的信息

**Comment by jachinlin** [comment]
`–v` 参数别去掉，需要挂在数据卷
