### ISSUE TITLE
生成mobi失败

### ISSUE THREAD

**Issue by cr7mufc520** [jachinlin/geektime_dl#43]
`docker run -v `pwd`:/output -it --rm geektime ebookbatch --all --enable-comments`可以把html和图片下载下来，但是 @生成mobi失败，提示“Expecting value: line 1 column 1 (char 0)”
![image](https://user-images.githubusercontent.com/50861832/63146589-023b9a80-c02e-11e9-8e05-8ad057bf5172.png)

**Comment by jachinlin** [comment]
@cr7mufc520 重新build下镜像吧 你用的应该是旧的版本，现在已经没有 cookie.json 和 sqlite3.db 两个文件了
