### ISSUE TITLE
ERROR: 'gbk' codec can't encode character '\U0001f601' in position 7008: illegal multibyte sequence

### ISSUE THREAD

**Issue by lazeyliu** [jachinlin/geektime_dl#45]
![image](https://user-images.githubusercontent.com/5097837/63853552-9bbf6080-c9cd-11e9-96d1-92d3a9bfebf4.png)

**Comment by lazeyliu** [comment]
已解决
![image](https://user-images.githubusercontent.com/5097837/63854310-7a5f7400-c9cf-11e9-85cd-9826c5b9701b.png)

**Comment by jachinlin** [comment]
@lazeyliu 提个pr吧
