### ISSUE TITLE
能否提供缩小图片的功能，这样能够减少最终生成的电子书的大小

### ISSUE THREAD

**Issue by kerraway** [jachinlin/geektime_dl#46]
试着做了几个电子书，发现很多都超过 50M 了，kindle 好像对电子书的大小有一定限制。

我试着在 Mac 上用 PicConvert 将图片缩小到 70% 质量，然后再制作电子书，发现能否将最终的电子书大小缩小很多。

能否提供缩小图片的功能，以参数的形式，让用户能够选择是否将最终生成的电子书缩小一些。

对 Python 不太熟，我就不提 PR 了😂️。

**Comment by jachinlin** [comment]
done 
see #53 
usage:
`geektime ebook <course_id> --image-ratio=0.5`
