### ISSUE TITLE
kindlegen 无法在 macOS Catalina 10.15 运行

### ISSUE THREAD

**Issue by kerraway** [jachinlin/geektime_dl#52]
#### 问题描述
升级 macOS Catalina 10.15 后发现，kindlegen 无法运行。

#### 原因解释
macOS Catalina 10.15 不再支持 32 位应用，而亚马逊并没有升级 kindlegen。

#### 解决办法
亚马逊更新了 kindle-previewer，支持 macOS Catalina 10.15，而 kindle-previewer 的包里带有 kindlegen。
1. 卸载 kindlegen，如果是使用 brew 安装的话，使用以下命令：
```shell
brew cask uninstall kindlegen
```
2. 安装 kindle-previewer，使用 brew 安装命令如下：
```shell
brew cask install kindle-previewer
```
3. 为 kindle-previewer 包内的 kindlegen 添加软链接：
```shell
ln -s /Applications/Kindle\ Previewer\ 3.app/Contents/MacOS/lib/fc/bin/kindlegen /usr/local/bin/kindlegen
```
搞定，在终端运行 `kindlegen` 试下吧。

**Comment by jachinlin** [comment]
thx.

**Comment by scofield-hello** [comment]
按照你说的做了之后，仍然无法运行，你也是这个错误吗   @kerraway 
ERROR: [Errno 86] Bad CPU type in executable: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kindle_maker/bin/mac/kindlegen'

**Comment by jachinlin** [comment]
> 按照你说的做了之后，仍然无法运行，你也是这个错误吗 @kerraway
> ERROR: [Errno 86] Bad CPU type in executable: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kindle_maker/bin/mac/kindlegen'

@scofield-hello  kerraway说的是针对旧版本的geektime-dl，现在的最新的版本可以试下

```
// 删除旧的 kindlegen 
rm /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kindle_maker/bin/mac/kindlegen

//添加软链
ln -s /Applications/Kindle\ Previewer\ 3.app/Contents/MacOS/lib/fc/bin/kindlegen /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kindle_maker/bin/mac/kindlegen

```

**Comment by scofield-hello** [comment]
@jachinlin 按照你提出的解决办法做了之后问题解决了，谢谢！
