### ISSUE TITLE
执行login之后query和ebook均显示未invalid账户和密码

### ISSUE THREAD

**Issue by tor2016** [jachinlin/geektime_dl#58]

**Comment by jachinlin** [comment]
@tor2016 more context please

**Comment by tor2016** [comment]
Use 'geektime <command> --help' for individual command help.
(venv3) root@VM-0-2-ubuntu:~# geektime login
Login succeed
(venv3) root@VM-0-2-ubuntu:~# geektime query
ERROR: invalid geektime account or password
Use 'geektime login --help' for  help.
