### ISSUE TITLE
kindlegen 报错

### ISSUE THREAD

**Issue by poettian** [jachinlin/geektime_dl#61]
已经参考 #52 #57 的解决办法，但是仍然有些课程会报错。

系统：macos 10.15.3

报错信息如下：

<img width="1785" alt="WechatIMG39" src="https://user-images.githubusercontent.com/16424646/73564232-0eab9680-449a-11ea-96e9-ab1be058c1bb.png">

**Comment by jachinlin** [comment]
@poettian 
kindlegen 制作电子书 出现 warning 了，如果还想要该电子书的话，到如下路径（每次都不一样）找下
![gt](https://user-images.githubusercontent.com/18514879/74520571-ce94eb00-4f52-11ea-8db9-0e5aa2adb492.png)

bug 就不修改了，欢迎pr
