### ISSUE TITLE
一次性下载所有资料时如果出错应该使用跳过错误把？

### ISSUE THREAD

**Issue by wajika** [jachinlin/geektime_dl#62]
geektime ebook all 这样的命令，如果下载到一半出现错误，重新执行又要重新下载（不支持断点传输），下载到那个出错的地方又停止（无法忽略错误），这样不就一直恶性循环了吗？

另外对于现在很多的html结构还是存在解析的问题，是否考虑弄一个通用的结构解析引擎？

还有对于标题名字遇到&￥%之类的特殊符号可以识别吗？（比如深入拆解Tomcat & Jetty）

**Comment by jachinlin** [comment]
欢迎 pr
