### ISSUE TITLE
下载175视频时，只下载了几个文件 就结束了

### ISSUE THREAD

**Issue by wajika** [jachinlin/geektime_dl#63]
/usr/local/bin # geektime mp4 175 --hd-only --output-folder=/output
开始下载视频:175-Web协议详解与抓包实战
数据爬取中:Web协议详解与抓包:   0%|                                                                                                                                               | 0/121 [00:00<?, ?it/s]数据爬取中:Web协议详解与抓包: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 121/121 [00:00<00:00, 1412.87it/s]
ERROR: 'str' object has no attribute 'get'
视频下载中:02-内容综述:   0%|                                                                                                                                                      | 0/42 [00:00<?, ?it/s]         
视频下载中:01-课程介绍:   0%|                                                                                                                                                      | 0/36 [00:00<?, ?it/s]         
视频下载中:03-浏览器发起HT: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:21<00:00,  2.10it/s]视频下载中:01-课程介绍:  61%|██████████████████████████████████████████████████████████████████████████████████████▏                                                      | 22/36 [00:20<00:12,  1.15it/s]
视频下载中:02-内容综述: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42/42 [00:22<00:00,  1.89it/s]视频下载中:01-课程介绍: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [00:37<00:00,  1.03s/it]
视频下载中:04-基于ABNF语: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:43<00:00,  2.06it/s]视频下载中:05-网络为什么要分: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:33<00:00,  1.89it/s]
/usr/local/bin #

**Comment by wajika** [comment]
已经下载的文件列表

[root@kafka1 Web协议详解与抓包实战]# ls -lh
total 511M
-rw-r--r-- 1 root root 143M Mar  9 01:14 01-课程介绍.hd.ts
-rw-r--r-- 1 root root  75M Mar  9 00:37 01-课程介绍.sd.ts
-rw-r--r-- 1 root root  13M Mar  9 01:14 02-内容综述.hd.ts
-rw-r--r-- 1 root root  13M Mar  9 00:36 02-内容综述.sd.ts
-rw-r--r-- 1 root root  18M Mar  9 01:14 03-浏览器发起HTTP请求的典型场景.hd.ts
-rw-r--r-- 1 root root  18M Mar  9 00:36 03-浏览器发起HTTP请求的典型场景.sd.ts
-rw-r--r-- 1 root root  50M Mar  9 01:14 04-基于ABNF语义定义的HTTP消息格式.hd.ts
-rw-r--r-- 1 root root  49M Mar  9 00:37 04-基于ABNF语义定义的HTTP消息格式.sd.ts
-rw-r--r-- 1 root root  36M Mar  9 01:15 05-网络为什么要分层：OSI模型与TCPIP模型.hd.ts
-rw-r--r-- 1 root root  36M Mar  9 00:37 05-网络为什么要分层：OSI模型与TCPIP模型.sd.ts
-rw-r--r-- 1 root root  64M Mar  9 00:38 09-如何用Chrome的Network面板分析HTTP报文.sd.ts

**Comment by xiaosTyy** [comment]
极客视频已经修复了非加密的视频文件暴露，现在都是采用了阿里的DRM加密的视频文件。你能下载的都是暴露出去的免费视频

**Comment by xiaosTyy** [comment]
> 已经下载的文件列表
> 
> [root@ Web协议详解与抓包实战]# ls -lh
> total 511M
> -rw-r--r-- 1 root root 143M Mar 9 01:14 01-课程介绍.hd.ts
> -rw-r--r-- 1 root root 75M Mar 9 00:37 01-课程介绍.sd.ts
> -rw-r--r-- 1 root root 13M Mar 9 01:14 02-内容综述.hd.ts
> -rw-r--r-- 1 root root 13M Mar 9 00:36 02-内容综述.sd.ts
> -rw-r--r-- 1 root root 18M Mar 9 01:14 03-浏览器发起HTTP请求的典型场景.hd.ts
> -rw-r--r-- 1 root root 18M Mar 9 00:36 03-浏览器发起HTTP请求的典型场景.sd.ts
> -rw-r--r-- 1 root root 50M Mar 9 01:14 04-基于ABNF语义定义的HTTP消息格式.hd.ts
> -rw-r--r-- 1 root root 49M Mar 9 00:37 04-基于ABNF语义定义的HTTP消息格式.sd.ts
> -rw-r--r-- 1 root root 36M Mar 9 01:15 05-网络为什么要分层：OSI模型与TCPIP模型.hd.ts
> -rw-r--r-- 1 root root 36M Mar 9 00:37 05-网络为什么要分层：OSI模型与TCPIP模型.sd.ts
> -rw-r--r-- 1 root root 64M Mar 9 00:38 09-如何用Chrome的Network面板分析HTTP报文.sd.ts

极客视频已经修复了非加密的视频文件暴露，现在都是采用了阿里的DRM加密的视频文件。你能下载的都是暴露出去的免费视频

**Comment by wajika** [comment]
@xiaosTyy 谢谢回复
