### ISSUE TITLE
生成电子书的笔记导出问题

### ISSUE THREAD

**Issue by amanda94** [jachinlin/geektime_dl#70]
在kindle 上的标注和笔记 不能导出 
![image](https://user-images.githubusercontent.com/14306912/79540929-8497c500-80bb-11ea-8c8a-2dce623e13a4.png)
目前用的是 kindle 的mac 版本

似乎是和版权限制有关的 猜测是依赖 kindlegen 生成电子书时引入的 因为 我尝试着 直接用kindlegen 命令行  生成的 mobi 文件 同样遇到了此限制
没有看到 [kindlegen的文档](https://kindlegen.s3.amazonaws.com/docs/english/Readme.txt) 上提供什么相应的说明

不知其他人是否碰到此问题 有没有什么好的解决办法

**Comment by jachinlin** [comment]
建议将语言调为英文，然后copy+google

**Comment by amanda94** [comment]
能详细说明下吗？kindle 的电脑客户端设置里并没有找到语言方面的设置。这里是指电脑的系统设置吗？
还有你提到的 copy+google 是指什么呢？放弃笔记和标注？
