### ISSUE TITLE
geektime ebook 126报错 ERROR: [Errno 22] Invalid argument: 'D:\\software\\venv3\\Scripts\\ebook\\数据结构与算法之美\\06-链表（上）：

### ISSUE THREAD

**Issue by black2567** [jachinlin/geektime_dl#75]
![image](https://user-images.githubusercontent.com/46598378/85270820-76e03080-b4ac-11ea-9240-8b011e3ceeb7.png)

**Comment by jachinlin** [comment]
sorry 1、没有window系统，2、没购买126专栏，无法进行调试，建议直接使用docker

或者帮忙修复下，然后提个pr


感谢
