### ISSUE TITLE
ERROR: 'gbk' codec can't encode character '\xa5' in position 2142: illegal multibyte sequence

### ISSUE THREAD

**Issue by husanfeng** [jachinlin/geektime_dl#79]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wutinglong** [comment]
同问，也是这个问题

**Comment by cuipengfei** [comment]
Docker里面跑，ok了
