### ISSUE TITLE
报错：ERROR: create_chapter() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by xushuhui** [jachinlin/geektime_dl#86]
Python 3.6.9，WSL
执行 geektime ebook xx后html下载下来，但是报错 ERROR: create_chapter() takes 2 positional arguments but 3 were given

感谢你开源项目

**Comment by jachinlin** [comment]
> Python 3.6.9，WSL
> 执行 geektime ebook xx后html下载下来，但是报错 ERROR: create_chapter() takes 2 positional arguments but 3 were given
> 
> 感谢你开源项目

没精力维护了，欢迎 pr

**Comment by xushuhui** [comment]
python实在不会，已用go重写 https://github.com/xushuhui/geektime-ebook
