### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by wajika** [jachinlin/geektime_dl#9]
**Is your feature request related to a problem? Please describe.**
系统版本：CentOS Linux release 7.5.1804 (Core) 
python版本3.7.1
**Describe the solution you'd like**
直接运行geektime login或是加上--account和--password参数，都会提示maximum recursion depth exceeded
**Describe alternatives you've considered**

**Additional context**
/root/venv3/lib/python3.7/site-packages/geektime_dl/utils/m3u8_downloader.py:5: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/root/venv3/lib/python3.7/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (/root/venv3/lib/python3.7/site-packages/urllib3/util/ssl_.py)']. 
  monkey.patch_all()
maximum recursion depth exceeded

**Comment by jachinlin** [comment]
Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See gevent/gevent#1016.

py3.6+ 还有问题
试下py3.5吧

**Comment by jachinlin** [comment]
fixed
