### ISSUE TITLE
非法图形验证码

### ISSUE THREAD

**Issue by JamesBrosy** [jachinlin/geektime_dl#94]
+ 我输入账号和密码之后显示如下错误：
```
gk api fail:非法图形验证码
Enter again
```
+ 继续输入账号和密码之后依然显示：
```
ERROR：gk api fail:非法图形验证码
```

**Comment by JamesBrosy** [comment]
+ 初步解决方案
  减缓爬取的速度，等一小会儿，再重新登录

**Comment by hiifong** [comment]
> * 我输入账号和密码之后显示如下错误：
> 
> ```
> gk api fail:非法图形验证码
> Enter again
> ```
> 
> * 继续输入账号和密码之后依然显示：
> 
> ```
> ERROR：gk api fail:非法图形验证码
> ```

ERROR: gk api fail:非法图形验证码 我也遇到了，现在是有滑动验证了

**Comment by cuipengfei** [comment]
把cookie从浏览器扒拉出来，写死到代码里
